### ISSUE TITLE
@ListenPoint 无法获取到子注解的属性值（例如） @InsertListenPoint

### ISSUE THREAD

**Issue by JKwangzhicheng** [wanwujiedao/spring-boot-starter-canal#2]
![image](https://user-images.githubusercontent.com/26532131/55879919-3f9ca100-5bd2-11e9-9665-0970ca1235ee.png)

**Comment by JKwangzhicheng** [comment]
1. @InsertListenPoint(destination = "example", schema = "food", table = "async_task")

2. @ListenPoint(destination = "example", schema = "food", table = "async_task", eventType = CanalEntry.EventType.INSERT)

亲测第一种用法不生效，需要使用第二种用法

**Comment by wanwujiedao** [comment]
谢谢指正，最近比较忙，等我闲了看看原因，当时我都有测过的，我换了一个电脑，所以不知道代码是不是最新的

**Comment by wanwujiedao** [comment]
> 1. @InsertListenPoint(destination = "example", schema = "food", table = "async_task")
> 2. @ListenPoint(destination = "example", schema = "food", table = "async_task", eventType = CanalEntry.EventType.INSERT)
> 
> 亲测第一种用法不生效，需要使用第二种用法

我这边测试了一下，是可以的，你在这边打个断点看看

```java

	/**
	 * 初始化监听器
	 *
	 * @param
	 * @return
	 * @author 阿导
	 * @time 2018/5/28 14:53
	 * @CopyRight 万物皆导
	 */
	private void initListeners() {
		logger.info("{}: 监听器正在初始化....", Thread.currentThread().getName());
		//获取监听器
		List<CanalEventListener> list = BeanUtil.getBeansOfType(CanalEventListener.class);
		//若没有任何监听的，我也不知道引入这个 jar 干什么，直接返回吧
		if (list != null) {
			//若存在目标监听，放入 listenerMap
			listeners.addAll(list);
		}
		
		//若是你喜欢通过注解的方式去监听的话。。
		Map<String, Object> listenerMap = BeanUtil.getBeansWithAnnotation(com.wwjd.starter.canal.annotation.CanalEventListener.class);
		//也放入 map
		if (listenerMap != null) {
			for (Object target : listenerMap.values()) {
				//方法获取
				Method[] methods = target.getClass().getDeclaredMethods();
				if (methods != null && methods.length > 0) {
					for (Method method : methods) {
						//获取监听的节点
						ListenPoint l = AnnotationUtils.findAnnotation(method, ListenPoint.class);
						if (l != null) {
							annoListeners.add(new ListenerPoint(target, method, l));
						}
					}
				}
			}
		}
		//初始化监听结束
		logger.info("{}: 监听器初始化完成.", Thread.currentThread().getName());
		//整个项目上下文都没发现监听器。。。
		if (logger.isWarnEnabled() && listeners.isEmpty() && annoListeners.isEmpty()) {
			logger.warn("{}: 该项目中没有任何监听的目标! ", Thread.currentThread().getName());
		}
	}

```

**Comment by wanwujiedao** [comment]
![image](https://user-images.githubusercontent.com/15843869/57513487-f494bb80-7340-11e9-8111-bc1d4aa7c9c7.png)

这个是注解的一些用法，和本项目主旨关系不大，这个是能获取子类注解的方法的，这边是我调式的截图。另外
```java
AnnotationUtils.findAnnotation(method, ListenPoint.class);

```
这里会根据方法上面的注解匹配其是否是入参传入的注解的本身或者是其子类，若是则添加到集合，这块逻辑也是没有问题的。
![image](https://user-images.githubusercontent.com/15843869/57514267-ae405c00-7342-11e9-8def-e0c2b1aed77d.png)

**Comment by wanwujiedao** [comment]
我大概知道你的意思的，我排查下原因，谢谢

**Comment by wanwujiedao** [comment]
![image](https://user-images.githubusercontent.com/15843869/57623229-edc8ab80-75c1-11e9-8bca-c780c9ede6cd.png)

**Comment by wanwujiedao** [comment]
> 1. @InsertListenPoint(destination = "example", schema = "food", table = "async_task")
> 2. @ListenPoint(destination = "example", schema = "food", table = "async_task", eventType = CanalEntry.EventType.INSERT)
> 
> 亲测第一种用法不生效，需要使用第二种用法

已经解决了，谢谢指正
