### ISSUE TITLE
项目无法启动

### ISSUE THREAD

**Issue by miaomiaojianglove** [wanwujiedao/spring-boot-starter-canal#3]
Error creating bean with name 'canalClient' defined in com.wwjd.starter.canal.config.CanalClientConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.wwjd.starter.canal.client.interfaces.CanalClient]: Factory method 'canalClient' threw exception; nested exception is com.alibaba.otter.canal.protocol.exception.CanalClientException: failed to subscribe with reason: something goes wrong with channel:[id: 0x2b01167c, /60.177.121.116:60677 => /xxxxxxx:11111], exception=com.alibaba.otter.canal.server.exception.CanalServerException: destination:wwjd should start first

**Comment by LONGHEIHEI** [comment]
请问这个解决了吗

**Comment by wanwujiedao** [comment]
我没有这个问题呀。。。

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by LONGHEIHEI** [comment]
会不会我用Canal是1.1.3版本的原因？

**Comment by miaomiaojianglove** [comment]
大佬你好我这边就是一直跑不起来但是用al阿里原生的canal 就能直接订阅数据 您说的那个联不通 我也是一脸懵逼 我下面有个详细错误的截图您可以看下



------------------ 原始邮件 ------------------
发件人: "阿导"<notifications@github.com>; 
发送时间: 2019年4月23日(星期二) 下午5:28
收件人: "wanwujiedao/spring-boot-starter-canal"<spring-boot-starter-canal@noreply.github.com>; 
抄送: "神秘的凯"<469781936@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [wanwujiedao/spring-boot-starter-canal] 项目无法启动 (#3)



我没有这个问题呀。。。 
 
 获取Outlook for Android< https://aka. ms/ghei36> ;  
 
 ________________________________

**Comment by miaomiaojianglove** [comment]
还没有了 一直在等楼主回复




------------------ 原始邮件 ------------------
发件人: "LongShengWen"<notifications@github.com>; 
发送时间: 2019年4月23日(星期二) 下午4:51
收件人: "wanwujiedao/spring-boot-starter-canal"<spring-boot-starter-canal@noreply.github.com>; 
抄送: "神秘的凯"<469781936@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [wanwujiedao/spring-boot-starter-canal] 项目无法启动 (#3)




请问这个解决了吗

**Comment by miaomiaojianglove** [comment]
大佬方便留个联系方式吗 万分感谢

**Comment by LONGHEIHEI** [comment]
这个问题我解决了，配置文件的问题
canal:
  client:
    instances:
      example:
        clusterEnabled: false
        host: 
        port: 11111
        batchSize: 1000
        acquireInterval: 1000
        retryCount: 20
        user-name:
        password:

这里的example应该配置成你的canal模板的名称

**Comment by miaomiaojianglove** [comment]
> 这个问题我解决了，配置文件的问题
> canal:
> client:
> instances:
> example:
> clusterEnabled: false
> host:
> port: 11111
> batchSize: 1000
> acquireInterval: 1000
> retryCount: 20
> user-name:
> password:
> 
> 这里的example应该配置成你的canal模板的名称

是canal的官方配置文件嘛

**Comment by miaomiaojianglove** [comment]
> 这个问题我解决了，配置文件的问题
> canal:
> client:
> instances:
> example:
> clusterEnabled: false
> host:
> port: 11111
> batchSize: 1000
> acquireInterval: 1000
> retryCount: 20
> user-name:
> password:
> 
> 这里的example应该配置成你的canal模板的名称

请问下这个配置文件是哪里的？ 谢谢了

**Comment by LONGHEIHEI** [comment]
> > 这个问题我解决了，配置文件的问题
> > canal:
> > client:
> > instances:
> > example:
> > clusterEnabled: false
> > host:
> > port: 11111
> > batchSize: 1000
> > acquireInterval: 1000
> > retryCount: 20
> > user-name:
> > password:
> > 这里的example应该配置成你的canal模板的名称
> 
> 请问下这个配置文件是哪里的？ 谢谢了

SpringBoot 的配置文件啊

**Comment by miaomiaojianglove** [comment]
![image](https://user-images.githubusercontent.com/28811199/56644094-94014f80-66ad-11e9-94ae-9246d595a41d.png)
配置文件 内没有这个配置呀

**Comment by miaomiaojianglove** [comment]
> > > 这个问题我解决了，配置文件的问题
> > > canal:
> > > client:
> > > instances:
> > > example:
> > > clusterEnabled: false
> > > host:
> > > port: 11111
> > > batchSize: 1000
> > > acquireInterval: 1000
> > > retryCount: 20
> > > user-name:
> > > password:
> > > 这里的example应该配置成你的canal模板的名称
> > 
> > 
> > 请问下这个配置文件是哪里的？ 谢谢了
> 
> SpringBoot 的配置文件啊

![image](https://user-images.githubusercontent.com/28811199/56644181-c3b05780-66ad-11e9-90d5-07861f3d68dc.png)
配置文件内并没有这个配置呀 老哥是怎么弄的 在配置类内建了个属性吗

**Comment by LONGHEIHEI** [comment]
> > > > 这个问题我解决了，配置文件的问题
> > > > canal:
> > > > client:
> > > > instances:
> > > > example:
> > > > clusterEnabled: false
> > > > host:
> > > > port: 11111
> > > > batchSize: 1000
> > > > acquireInterval: 1000
> > > > retryCount: 20
> > > > user-name:
> > > > password:
> > > > 这里的example应该配置成你的canal模板的名称
> > > 
> > > 
> > > 请问下这个配置文件是哪里的？ 谢谢了
> > 
> > 
> > SpringBoot 的配置文件啊
> 
> ![image](https://user-images.githubusercontent.com/28811199/56644181-c3b05780-66ad-11e9-90d5-07861f3d68dc.png)
> 配置文件内并没有这个配置呀 老哥是怎么弄的 在配置类内建了个属性吗

把wwjd 改成你服务器canal应用的配置文件模板的名称，可能你的也是example，你可以试试

**Comment by miaomiaojianglove** [comment]
------------------ 原始邮件 ------------------
发件人: "LongShengWen"<notifications@github.com>;
发送时间: 2019年4月24日(星期三) 下午4:30
收件人: "wanwujiedao/spring-boot-starter-canal"<spring-boot-starter-canal@noreply.github.com>;
抄送: "神秘的凯"<469781936@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [wanwujiedao/spring-boot-starter-canal] 项目无法启动 (#3)



    
这个问题我解决了，配置文件的问题
 canal:
 client:
 instances:
 example:
 clusterEnabled: false
 host:
 port: 11111
 batchSize: 1000
 acquireInterval: 1000
 retryCount: 20
 user-name:
 password:
 这里的example应该配置成你的canal模板的名称
  
请问下这个配置文件是哪里的？ 谢谢了
  
SpringBoot 的配置文件啊
  

 配置文件内并没有这个配置呀 老哥是怎么弄的 在配置类内建了个属性吗
  
把wwjd 改成你服务器canal应用的配置文件模板的名称，可能你的也是example，你可以试试
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.





是这么改吗 还是不行呀

**Comment by miaomiaojianglove** [comment]
> > > > > 这个问题我解决了，配置文件的问题
> > > > > canal:
> > > > > client:
> > > > > instances:
> > > > > example:
> > > > > clusterEnabled: false
> > > > > host:
> > > > > port: 11111
> > > > > batchSize: 1000
> > > > > acquireInterval: 1000
> > > > > retryCount: 20
> > > > > user-name:
> > > > > password:
> > > > > 这里的example应该配置成你的canal模板的名称
> > > > 
> > > > 
> > > > 请问下这个配置文件是哪里的？ 谢谢了
> > > 
> > > 
> > > SpringBoot 的配置文件啊
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/28811199/56644181-c3b05780-66ad-11e9-90d5-07861f3d68dc.png)
> > 配置文件内并没有这个配置呀 老哥是怎么弄的 在配置类内建了个属性吗
> 
> 把wwjd 改成你服务器canal应用的配置文件模板的名称，可能你的也是example，你可以试试

![image](https://user-images.githubusercontent.com/28811199/56644879-29511380-66af-11e9-95e5-72f61d516a60.png)
![image](https://user-images.githubusercontent.com/28811199/56644966-56052b00-66af-11e9-93c9-baaa0a10a8b7.png)
还行不行呢  老哥能吧你的配置文件截个图给我吗 万分感谢

**Comment by LONGHEIHEI** [comment]
> > > > > > 这个问题我解决了，配置文件的问题
> > > > > > canal:
> > > > > > client:
> > > > > > instances:
> > > > > > example:
> > > > > > clusterEnabled: false
> > > > > > host:
> > > > > > port: 11111
> > > > > > batchSize: 1000
> > > > > > acquireInterval: 1000
> > > > > > retryCount: 20
> > > > > > user-name:
> > > > > > password:
> > > > > > 这里的example应该配置成你的canal模板的名称
> > > > > 
> > > > > 
> > > > > 请问下这个配置文件是哪里的？ 谢谢了
> > > > 
> > > > 
> > > > SpringBoot 的配置文件啊
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/28811199/56644181-c3b05780-66ad-11e9-90d5-07861f3d68dc.png)
> > > 配置文件内并没有这个配置呀 老哥是怎么弄的 在配置类内建了个属性吗
> > 
> > 
> > 把wwjd 改成你服务器canal应用的配置文件模板的名称，可能你的也是example，你可以试试
> 
> ![image](https://user-images.githubusercontent.com/28811199/56644879-29511380-66af-11e9-95e5-72f61d516a60.png)
> ![image](https://user-images.githubusercontent.com/28811199/56644966-56052b00-66af-11e9-93c9-baaa0a10a8b7.png)
> 还行不行呢 老哥能吧你的配置文件截个图给我吗 万分感谢
<img width="1192" alt="WeChat35e616e98b48a5145c99379f1859317d" src="https://user-images.githubusercontent.com/29967080/56645249-ea6f8d80-66af-11e9-923b-a243c51bdd76.png">

**Comment by miaomiaojianglove** [comment]
> > > > > > 这个问题我解决了，配置文件的问题
> > > > > > canal:
> > > > > > client:
> > > > > > instances:
> > > > > > example:
> > > > > > clusterEnabled: false
> > > > > > host:
> > > > > > port: 11111
> > > > > > batchSize: 1000
> > > > > > acquireInterval: 1000
> > > > > > retryCount: 20
> > > > > > user-name:
> > > > > > password:
> > > > > > 这里的example应该配置成你的canal模板的名称
> > > > > 
> > > > > 
> > > > > 请问下这个配置文件是哪里的？ 谢谢了
> > > > 
> > > > 
> > > > SpringBoot 的配置文件啊
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/28811199/56644181-c3b05780-66ad-11e9-90d5-07861f3d68dc.png)
> > > 配置文件内并没有这个配置呀 老哥是怎么弄的 在配置类内建了个属性吗
> > 
> > 
> > 把wwjd 改成你服务器canal应用的配置文件模板的名称，可能你的也是example，你可以试试
> 
> ![image](https://user-images.githubusercontent.com/28811199/56644879-29511380-66af-11e9-95e5-72f61d516a60.png)
> ![image](https://user-images.githubusercontent.com/28811199/56644966-56052b00-66af-11e9-93c9-baaa0a10a8b7.png)
> 还行不行呢 老哥能吧你的配置文件截个图给我吗 万分感谢

![image](https://user-images.githubusercontent.com/28811199/56645372-260a5780-66b0-11e9-8309-509b74808377.png)
我这个模板已经设置了哦

**Comment by miaomiaojianglove** [comment]
> 这个问题我解决了，配置文件的问题
> canal:
> client:
> instances:
> example:
> clusterEnabled: false
> host:
> port: 11111
> batchSize: 1000
> acquireInterval: 1000
> retryCount: 20
> user-name:
> password:
> 
> 这里的example应该配置成你的canal模板的名称

org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.wwjd.starter.canal.client.interfaces.CanalClient]: Factory method 'canalClient' threw exception; nested exception is com.alibaba.otter.canal.protocol.exception.CanalClientException: failed to subscribe with reason: something goes wrong with channel:[id: 0x23a15d62, /60.176.88.99:6853 => /118.31.165.113:11111], exception=com.alibaba.otter.canal.server.exception.CanalServerException: destination:wwjd should start first

destination:wwjd should start first

这个是我目前编辑器启动报的错误

**Comment by miaomiaojianglove** [comment]
问题解决了 要将 canal.client.instances.wwjd改成 canal.client.instances.example  感谢各位大佬的解答

**Comment by wanwujiedao** [comment]
哈哈，我都忘了这个配置，这个是我自定义的一个配置，因为我喜欢用 万物皆导作为 ID ,所以简写 wwjd，对你造成的困扰，我表示抱歉，解决就好

**Comment by miaomiaojianglove** [comment]
> 哈哈，我都忘了这个配置，这个是我自定义的一个配置，因为我喜欢用 万物皆导作为 ID ,所以简写 wwjd，对你造成的困扰，我表示抱歉，解决就好

哈哈哈 建议老哥在RedME内写下 不然刚刚接手可能会莫名的懵逼下   另外恳请下大佬将这个项目加上改变前的数据返回这个功能 我看了下接口目前只能返回变动后的数据 如果能返回变动前的数据就更好了  万分感谢

**Comment by wanwujiedao** [comment]
> > 哈哈，我都忘了这个配置，这个是我自定义的一个配置，因为我喜欢用 万物皆导作为 ID ,所以简写 wwjd，对你造成的困扰，我表示抱歉，解决就好
> 
> 哈哈哈 建议老哥在RedME内写下 不然刚刚接手可能会莫名的懵逼下 另外恳请下大佬将这个项目加上改变前的数据返回这个功能 我看了下接口目前只能返回变动后的数据 如果能返回变动前的数据就更好了 万分感谢

谢谢你的提议，大佬不敢当，那个配置是 spring 里面的知识，你提议的是在更新或者是删除的时候添加这个变更前的数据吗？我找个时间看下

**Comment by miaomiaojianglove** [comment]
> 你提议的是在更新或者是删
嗯嗯是的  如果某条数据删除 和更新能够返回 更新前和删除后的数据就好了 因为这样的话使用这个项目的人如果有异步同步或者备份容灾功能这个返回历史数据就相当有用了 类似于回收站的功能 另外感谢大佬对开源社区的贡献 没啥好说的 给大佬磕俩头吧  噗通~砰 砰 砰 膜拜  另外恳请大佬将项目关联到国内的码云上一下  那里国内开发者多 而且方便留言交流  再次感谢
